package com.example.user_management.Model;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

// provides annotations and classes for working with persistence (database interactions),
// such as @Entity, @Id, and @GeneratedValue.
import jakarta.persistence.*;
// imported to represent date and time without time-zone information.
// It will be used for tracking creation and update timestamps.
import java.time.LocalDateTime;

@Entity // This annotation marks the User class as a JPA entity, meaning it maps to a database table.
@Table (name = "users")
public class User {
    @Id // This annotation specifies the primary key of the User entity

    // Specifies that the ID should be automatically generated by the database using an identity column.
    // This approach lets the database handle ID generation, typically by auto-incrementing it.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank (message = "Name can not be empty")
    @Size(max = 100, message = "Name can not be more than 100 characters")
    @Column (nullable = false, length = 100)
    private String name;

    @NotBlank (message = "Email is required")
    @Email (message = "Email should be valid")
    @Column (nullable = false, length = 255, unique = true)
    private String email;

    @NotBlank (message = "Password is required")
    @Size(min = 8, message = "Password must be at least 8 characters")
    @Column (nullable = false)
    private String password;

    @Column (name = "created_date", nullable = false, updatable = false)
    private LocalDateTime createdDate = LocalDateTime.now();

    @Column (name = "updated_date")
    private LocalDateTime updatedDate = LocalDateTime.now();

    @PreUpdate // annotation ensures updatedDate is set to the current time whenever the entity is updated.
    public void preUpdate(){
        updatedDate = LocalDateTime.now();
    }

    // Getters and Setters
    public Long getId(){
        return id;
    }
    public void setId(Long id){
        this.id = id;
    }

    public String getName(){
        return name;
    }
    public void setName(String name){
        this.name = name;
    }

    public String getEmail(){
        return email;
    }
    public void setEmail(String email){
        this.email = email;
    }

    public String getPassword(){
        return password;
    }
    public void setPassword(String password){
        this.password = password;
    }

    public LocalDateTime getCreatedDate(){
        return createdDate;
    }
    public void setCreatedDate(LocalDateTime createdDate){
        this.createdDate = createdDate;
    }

    public LocalDateTime getUpdatedDate(){
        return updatedDate;
    }
    public void setUpdatedDate(LocalDateTime updatedDate){
        this.updatedDate = updatedDate;
    }
}
